name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests

    - name: Generar reporte de pruebas
      run: |
        pip install coverage
        coverage run -m unittest discover -s tests
        coverage report -m
    
    - name: Verificar resultado de pruebas
      if: always()
      run: |
        if [ ${{ steps.correr-pruebas.outcome }} == 'failure' ]; then
          echo "Falla en las pruebas. el PR no se puede completar."
          exit 1
        fi      
